"""Short, exact-match claim identifiers for gift purchases."""

from __future__ import annotations

import secrets

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.config import settings
from app.database.models import GuestPurchase


GIFT_CLAIM_CODE_BYTES = 9
GIFT_CLAIM_CODE_LENGTH = 12
GIFT_DEEP_LINK_PREFIX = 'GIFT_'

# Compatibility with links emitted before claim_code was introduced. Those links
# contained the first 12 base64url characters of GuestPurchase.token.
GIFT_LEGACY_TOKEN_PREFIX_LENGTH = 12

# Long token prefixes remain supported for links generated by installations that
# used Telegram's 64-character start parameter capacity correctly.
GIFT_LONG_TOKEN_PREFIX_MIN_LENGTH = 48


def generate_gift_claim_code() -> str:
    """Return a compact 72-bit URL-safe bearer code (12 characters)."""
    code = secrets.token_urlsafe(GIFT_CLAIM_CODE_BYTES)
    if len(code) != GIFT_CLAIM_CODE_LENGTH:  # pragma: no cover - CPython invariant
        raise RuntimeError('Unexpected gift claim code length')
    return code


def gift_public_code(purchase: GuestPurchase) -> str:
    """Return the public claim code, falling back for pre-migration objects."""
    claim_code = getattr(purchase, 'claim_code', None)
    if claim_code and len(claim_code) == GIFT_CLAIM_CODE_LENGTH:
        return claim_code
    return purchase.token[:GIFT_LEGACY_TOKEN_PREFIX_LENGTH]


def build_gift_bot_link(purchase: GuestPurchase) -> str | None:
    """Build a compact Telegram deep link for a claimable gift."""
    bot_username = settings.get_bot_username()
    if not bot_username:
        return None
    return f'https://t.me/{bot_username}?start={GIFT_DEEP_LINK_PREFIX}{gift_public_code(purchase)}'


def build_gift_web_link(purchase: GuestPurchase) -> str | None:
    """Build the cabinet activation URL understood by the current MiniApp."""
    cabinet_base = (settings.CABINET_URL or '').rstrip('/')
    if not cabinet_base:
        return None
    return f'{cabinet_base}/gift?tab=activate&code={gift_public_code(purchase)}'


def is_supported_gift_claim_identifier(identifier: str) -> bool:
    """Return whether an identifier belongs to a supported claim-link format."""
    length = len(identifier)
    return length == GIFT_CLAIM_CODE_LENGTH or length >= GIFT_LONG_TOKEN_PREFIX_MIN_LENGTH


async def ensure_gift_claim_code(db: AsyncSession, purchase: GuestPurchase) -> str:
    """Assign and flush a short claim code when an older gift has none."""
    if purchase.claim_code and len(purchase.claim_code) == GIFT_CLAIM_CODE_LENGTH:
        return purchase.claim_code
    if not purchase.is_gift:
        raise ValueError('Claim codes are only available for gifts')

    # A collision is cryptographically negligible, but checking keeps the unique
    # index from turning it into a failed transaction if it ever happens.
    for _ in range(5):
        candidate = generate_gift_claim_code()
        result = await db.execute(select(GuestPurchase.id).where(GuestPurchase.claim_code == candidate).limit(1))
        if result.scalar_one_or_none() is None:
            purchase.claim_code = candidate
            await db.flush()
            return candidate
    raise RuntimeError('Unable to allocate a unique gift claim code')


async def get_gift_by_claim_identifier(
    db: AsyncSession,
    identifier: str,
    *,
    for_update: bool = False,
) -> GuestPurchase | None:
    """Resolve a gift by exact claim code or a supported legacy token form.

    New links always use the unique 12-character ``claim_code`` and therefore
    perform an exact indexed lookup. Token-prefix matching exists only for
    already issued legacy links.
    """
    identifier = identifier.strip()
    if not is_supported_gift_claim_identifier(identifier):
        return None

    if len(identifier) == GIFT_CLAIM_CODE_LENGTH:
        # Prefer the exact public code. If it does not exist, fall back to links
        # created before claim_code was introduced; those exposed the first 12
        # characters of the internal token.
        exact_statement = (
            select(GuestPurchase)
            .options(selectinload(GuestPurchase.tariff))
            .where(GuestPurchase.claim_code == identifier, GuestPurchase.is_gift.is_(True))
            .limit(1)
        )
        if for_update:
            exact_statement = exact_statement.with_for_update()
        exact_result = await db.execute(exact_statement)
        exact_match = exact_result.scalar_one_or_none()
        if exact_match is not None:
            return exact_match
        token_filter = GuestPurchase.token.startswith(identifier)
    elif len(identifier) >= 64:
        token_filter = GuestPurchase.token == identifier
    else:
        token_filter = GuestPurchase.token.startswith(identifier)

    statement = (
        select(GuestPurchase)
        .options(selectinload(GuestPurchase.tariff))
        .where(token_filter, GuestPurchase.is_gift.is_(True))
        .limit(2)
    )
    if for_update:
        statement = statement.with_for_update()

    result = await db.execute(statement)
    matches = list(result.scalars().all())
    if len(matches) != 1:
        return None
    return matches[0]
